[package]
name = "rust_tree"
version = "0.1.0"
authors = ["huang825172 <1048035187@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
